#!/usr/bin/env python3

import os
import sys

from command import Command

def main():
    c = Command()
    parser = c.create_parser()
    args = parser.parse_args()
    c.run(args)

if __name__ == "__main__":
    main()
